### PR TITLE
merge instrument selection, netcode

### PR DESCRIPTION
**Pull request by dokxid**
haihai,

# READY FOR PROD? prod more like ヾ(≧▽≦*)o IYKYK

webcord_qpM6mWlSCK

### CODE REVIEW

**Comment by taukute** [comment]
ARE YOU READY TO GO TO \*RO\*

**Review by taukute — COMMENTED** [review]
yup looks good 






Sent from my iPhone

**Comment by daphnelucia** [comment]
LGTF SOON,,,,

**Comment by dokxid** [comment]
closes #2

**Pull request merged**
